select * from customer limit 29

-- Q1. What is the total revenue generated by male vs. female customers?
select gender , SUM(purchase_amount) as revenue
from customer
group by gender

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'YES'
  AND purchase_amount >= (
      SELECT AVG(purchase_amount)
      FROM customer
  );



  SELECT AVG(purchase_amount) AS average_purchase
FROM customer;


SELECT discount_applied, COUNT(*)
FROM customer
GROUP BY discount_applied;


SELECT customer_id, purchase_amount, discount_applied
FROM customer
WHERE discount_applied = 'YES';

SELECT DISTINCT discount_applied FROM customer;


SELECT customer_id, purchase_amount
FROM customer
WHERE LOWER(discount_applied) = 'yes'
  AND purchase_amount >= (
      SELECT AVG(purchase_amount)
      FROM customer
  );


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND (AVG(review_rating::numeric),2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY avg(review_rating) DESC
LIMIT 5;


-- Q4. Compare the average purchase amount between Standard and Express Shipping.
-- Q4. Compare the average purchase amounts between Standard and Express Shipping.
SELECT shipping_type,
       ROUND(AVG(purchase_amount), 2)
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
       COUNT(customer_id) as total_customers,
       ROUND(AVG(purchase_amount), 2) as avg_spend,
       ROUND(SUM(purchase_amount), 2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND((SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0) / COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
case
    when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
end as customer_segment
from customer
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;


-- Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select category,
       item_purchased,
       COUNT(customer_id) as total_orders,
       ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
       count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;


-- Q10. What is the revenue contribution of each age group?
select age_group,
       SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;
